### ISSUE TITLE
Résultats de recherche innapropriés pour les chapitres

### ISSUE THREAD

**Issue by Lilounette** [betagouv/science-infuse#15]
Lors d'une recherche sur Science Infuse, les résultats de recherche de l'onglet "chapitres" remontent des résultats sans rapports avec la requête effectuée.
Par exemple si je tape "intelligence artificielle" je trouve un chapitre sur la biodiversité et son évolution qui n'ont pas de rapport avec le sujet. Mieux vaut ne rien afficher dans ce cas.

**Comment by boehm-e** [comment]
Fixed
